apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-ipsg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-ipsg
    app.kubernetes.io/part-of: mc-two-scenarios
  name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-ipsg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-ipsg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-ipsg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-aepv-tenant/mc-two-scenarios/devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-ipsg@sha256:ee1a2a67062869ea197908fe059b7d82cc34fd3063a6dae6a5148bc01a171d03
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
